"""
app/vector_store/chroma_store.py — ChromaDB Vector Store

[Concept: Vector Database Implementation]

────────────────────────────────────────────────────────────────
HOW VECTOR DATABASES WORK
────────────────────────────────────────────────────────────────
A vector database stores text as numerical vectors (embeddings).
Each embedding is a list of ~1500 floating-point numbers that
captures the SEMANTIC MEANING of the text.

  Text: "How many vacation days do employees get?"
  Embedding: [0.021, -0.143, 0.087, 0.234, ...]  (1536 numbers)

Two pieces of text that mean similar things will have embeddings
that point in similar directions in this high-dimensional space.

COSINE SIMILARITY measures how "similar" two vectors are:
  - Score of 1.0  = identical meaning
  - Score of 0.7+ = very similar
  - Score of 0.3- = unrelated

TOP-K RETRIEVAL:
  When a query comes in, we:
  1. Embed the query into a vector
  2. Compare it against ALL stored document vectors
  3. Return the K most similar ones (by cosine similarity score)

  This is extremely fast even with millions of documents because
  vector databases use approximate nearest neighbor (ANN) algorithms
  like HNSW (Hierarchical Navigable Small World).

ChromaDB stores:
  - The text content of each chunk
  - The embedding vector (generated by OpenAI or local model)
  - Metadata (doc_id, department, access_level) for filtering
────────────────────────────────────────────────────────────────
"""

import chromadb
from chromadb.config import Settings
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings
from langchain_core.documents import Document
from typing import List, Dict, Optional, Any

from app.config import (
    OPENAI_API_KEY, EMBEDDING_MODEL,
    CHROMA_PERSIST_DIR, COLLECTION_NAME, TOP_K_RESULTS
)
from app.observability.logger import logger


# ──────────────────────────────────────────────
# Embedding Model
# ──────────────────────────────────────────────

def get_embedding_function() -> OpenAIEmbeddings:
    """
    Return the embedding model used to convert text → vectors.

    We use OpenAI's text-embedding-ada-002 (1536 dimensions).
    This model is fast, cheap, and semantically rich.

    To swap to a different provider, replace this function.
    Example: return HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    """
    return OpenAIEmbeddings(
        model=EMBEDDING_MODEL,
        openai_api_key=OPENAI_API_KEY
    )


# ──────────────────────────────────────────────
# ChromaDB Store
# ──────────────────────────────────────────────

class VectorStore:
    """
    Wrapper around ChromaDB that handles:
      - Storing document chunks with metadata
      - Permission-filtered similarity search
      - Document listing and deletion
    """

    def __init__(self):
        self.embeddings = get_embedding_function()
        self._store: Optional[Chroma] = None

    def _get_store(self) -> Chroma:
        """
        Lazily initialize the ChromaDB store.
        Persists to disk so data survives server restarts.
        """
        if self._store is None:
            self._store = Chroma(
                collection_name=COLLECTION_NAME,
                embedding_function=self.embeddings,
                persist_directory=CHROMA_PERSIST_DIR,
            )
            logger.info(f"[VECTOR_STORE] Connected to ChromaDB at '{CHROMA_PERSIST_DIR}'")
        return self._store

    def add_documents(self, documents: List[Document]) -> List[str]:
        """
        Add a list of LangChain Document objects to ChromaDB.

        Each Document has:
          - page_content: the text of the chunk
          - metadata: dict with doc_id, title, department, access_level

        Returns list of assigned IDs.
        """
        store = self._get_store()
        ids = store.add_documents(documents)
        logger.info(f"[VECTOR_STORE] Added {len(documents)} chunks to ChromaDB")
        return ids

    def similarity_search(
        self,
        query: str,
        allowed_access_levels: List[str],
        k: int = TOP_K_RESULTS
    ) -> List[Dict[str, Any]]:
        """
        Search for the most semantically similar document chunks.

        ────────────────────────────────────────────────────────
        PERMISSION FILTERING (Key Security Feature)
        ────────────────────────────────────────────────────────
        The `allowed_access_levels` parameter is passed as a
        ChromaDB WHERE filter. This means the database itself
        enforces permissions at the query level — not at the
        application level after retrieval.

        This is important because:
          - Application-level filtering (retrieve all, then filter)
            risks leaking document content in logs/errors.
          - Database-level filtering means confidential docs are
            NEVER loaded into memory for unauthorized users.

        ChromaDB filter syntax:
          {"access_level": {"$in": ["public", "manager"]}}

        This returns only chunks where access_level is in the
        allowed list.
        ────────────────────────────────────────────────────────

        Args:
            query: The user's question (will be embedded automatically)
            allowed_access_levels: List of access levels user can see
            k: Number of top results to return

        Returns:
            List of dicts with 'content', 'metadata', 'score'
        """
        store = self._get_store()

        # Build the permission filter for ChromaDB
        # This is injected into the vector DB query itself
        if allowed_access_levels:
            where_filter = {"access_level": {"$in": allowed_access_levels}}
        else:
            # No allowed levels → return nothing (shouldn't reach LLM)
            return []

        try:
            # similarity_search_with_relevance_scores returns (Document, score) tuples
            results = store.similarity_search_with_relevance_scores(
                query=query,
                k=k,
                filter=where_filter
            )

            chunks = []
            for doc, score in results:
                chunks.append({
                    "content":     doc.page_content,
                    "metadata":    doc.metadata,
                    "score":       round(score, 4),
                })

            return chunks

        except Exception as e:
            logger.error(f"[VECTOR_STORE] Search error: {e}")
            return []

    # ──────────────────────────────────────────────
    # Sentence Window Retrieval — Neighbor Fetching
    #
    # WHY THIS METHOD EXISTS:
    # similarity_search finds the RIGHT chunk (precision). But a 500-char
    # chunk is often too narrow for a complete answer — the key sentence
    # may be cut off at the boundary. This method is the "expand" step:
    # given a matched chunk at index N, fetch [N-W … N+W] from the same
    # document using a direct metadata filter (not semantic search).
    #
    # This separates two concerns:
    #   - Finding  : small focused chunks → strong embedding signal
    #   - Reading  : wide passage         → complete context for the LLM
    # ──────────────────────────────────────────────

    def fetch_neighbors(
        self,
        doc_id: str,
        start_index: int,
        end_index: int,
        allowed_access_levels: List[str],
    ) -> List[tuple]:
        """
        Fetch a contiguous range of chunks from a single document by index.

        Uses a direct ChromaDB metadata filter — NOT vector similarity search.
        This means results are deterministic and always returned in document order.

        Args:
            doc_id:                 Source document to fetch from
            start_index:            First chunk_index to include (inclusive)
            end_index:              Last chunk_index to include (inclusive)
            allowed_access_levels:  Permission filter — re-applied here for
                                    defense-in-depth (same list as similarity_search)

        Returns:
            List of (chunk_index, content) tuples sorted by chunk_index.
            Returns [] if nothing found, access levels empty, or on error.
        """
        if not allowed_access_levels:
            return []

        store = self._get_store()
        try:
            collection = store._collection

            # $and is required when combining multiple field conditions in ChromaDB
            where_filter = {
                "$and": [
                    {"doc_id":       {"$eq":  doc_id}},
                    {"chunk_index":  {"$gte": start_index}},
                    {"chunk_index":  {"$lte": end_index}},
                    {"access_level": {"$in":  allowed_access_levels}},
                ]
            }

            result = collection.get(
                where=where_filter,
                include=["documents", "metadatas"]
            )

            # documents and metadatas lists are positionally aligned
            neighbors = []
            for content, meta in zip(result["documents"], result["metadatas"]):
                idx = meta.get("chunk_index", 0)
                neighbors.append((idx, content))

            # Sort by chunk_index so content is joined in document order
            neighbors.sort(key=lambda x: x[0])
            return neighbors

        except Exception as e:
            logger.error(f"[VECTOR_STORE] fetch_neighbors error doc_id={doc_id}: {e}")
            return []

    def list_documents(self) -> List[Dict]:
        """
        Return a summary of all stored documents.
        Groups chunks by doc_id to show one entry per document.
        """
        store = self._get_store()
        try:
            # Get all items from the collection
            collection = store._collection
            result = collection.get(include=["metadatas"])

            # Group by doc_id
            doc_map: Dict[str, Dict] = {}
            for meta in result["metadatas"]:
                doc_id = meta.get("doc_id", "unknown")
                if doc_id not in doc_map:
                    doc_map[doc_id] = {
                        "doc_id":       doc_id,
                        "title":        meta.get("title", "Unknown"),
                        "department":   meta.get("department", "Unknown"),
                        "access_level": meta.get("access_level", "public"),
                        "chunk_count":  0,
                    }
                doc_map[doc_id]["chunk_count"] += 1

            return list(doc_map.values())

        except Exception as e:
            logger.error(f"[VECTOR_STORE] List error: {e}")
            return []

    def delete_document(self, doc_id: str) -> int:
        """Remove all chunks for a given doc_id. Returns chunks deleted."""
        store = self._get_store()
        try:
            collection = store._collection
            result = collection.get(where={"doc_id": doc_id}, include=[])
            ids = result["ids"]
            if ids:
                collection.delete(ids=ids)
            logger.info(f"[VECTOR_STORE] Deleted {len(ids)} chunks for doc_id={doc_id}")
            return len(ids)
        except Exception as e:
            logger.error(f"[VECTOR_STORE] Delete error: {e}")
            return 0


# ──────────────────────────────────────────────
# Singleton instance
# ──────────────────────────────────────────────

vector_store = VectorStore()
